### ISSUE TITLE
User interface / experience

### ISSUE THREAD

**Issue by Su5eD** [Sinytra/Wiki#1]
```[tasklist]
### Tasks
- [ ] https://github.com/Sinytra/Wiki/issues/14
- [ ] https://github.com/Sinytra/Wiki/issues/7
- [ ] https://github.com/Sinytra/Wiki/issues/8
- [ ] https://github.com/Sinytra/Wiki/issues/9
- [ ] https://github.com/Sinytra/Wiki/issues/13
- [ ] https://github.com/Sinytra/Wiki/issues/10
- [ ] https://github.com/Sinytra/Wiki/issues/11
- [ ] https://github.com/Sinytra/Wiki/issues/12
```
