### ISSUE TITLE
Developer experience

### ISSUE THREAD

**Issue by Su5eD** [Sinytra/Wiki#2]
```[tasklist]
### Tasks
- [ ] https://github.com/Sinytra/Wiki/issues/19
- [ ] https://github.com/Sinytra/Wiki/issues/15
- [ ] https://github.com/Sinytra/Wiki/issues/16
- [ ] https://github.com/Sinytra/Wiki/issues/17
- [ ] https://github.com/Sinytra/Wiki/issues/18
- [ ] https://github.com/Sinytra/Wiki/issues/25
- [ ] https://github.com/Sinytra/Wiki/issues/27
- [ ] https://github.com/Sinytra/Wiki/issues/28
```
